### ISSUE TITLE
User and password

### ISSUE THREAD

**Issue by codeskin-r** [khaneliman/khanelinix#114]
I need help! I installed your configuration but I don't know what I have to put in username and password, help, thanks!

**Comment by khaneliman** [comment]
User should be whatever you set it up to be and if you didn't set a password, it defaults to 'password' in the module I believe.

**Comment by codeskin-r** [comment]
Thank you! I have another problem and I don't know what to do, I don't want
to give up, what should I do? It happened to me when I rebooted the system,
I'll send you an image

**Comment by codeskin-r** [comment]
![IMG-20240628-WA0011](https://github.com/khaneliman/khanelinix/assets/159903896/207857f5-30be-4c24-8c10-3a7c808d1ce9)

This si My problem, What should I do? Use NixOS gnome image without any window manager

**Comment by khaneliman** [comment]
> ![IMG-20240628-WA0011](https://private-user-images.githubusercontent.com/159903896/344352618-207857f5-30be-4c24-8c10-3a7c808d1ce9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2Njk0MDUsIm5iZiI6MTcxOTY2OTEwNSwicGF0aCI6Ii8xNTk5MDM4OTYvMzQ0MzUyNjE4LTIwNzg1N2Y1LTMwYmUtNGMyNC04YzEwLTNhN2M4MDhkMWNlOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOVQxMzUxNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTM5MTFmZThmNWU1MDkxNjI3MDcxN2VjMjQwNTE2ZDU4NTFkMTUzOGVjMGNiY2ZhMmQwZDZkZjQwMzk0NDEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CfXOdKsJOJMEQNSFMbHLPNr3MVLW282LDMucnezQJg4)
> 
> This si My problem, What should I do? Use NixOS gnome image without any window manager

Did you configure your hardware.nix to match your actual disk drives and partitions? It's looking for a partition named nixos to boot, which may not exist.

**Comment by khaneliman** [comment]
> I think the problem is that it doesn't replace the "hardware-configuration" file, how should I do that in your configuration? In what folder?

You should be adjusting the systems to fit your actual system. Example hardware..nix https://github.com/khaneliman/khanelinix/blob/main/systems/x86_64-linux/khanelinix/hardware.nix

**Comment by codeskin-r** [comment]
That is, do I have to edit that file by replacing the values to match my hardware configuration? Is it exactly that file that you are telling me about as an example?

**Comment by khaneliman** [comment]
> That is, do I have to edit that file by replacing the values to match my hardware configuration? Is it exactly that file that you are telling me about as an example?  

That file determines a few hardware specifics. You need to make sure the settings match your hardware configuration from cpu to gpu to hard drive partitioning and mount stuff.

**Comment by codeskin-r** [comment]
Do you think I should use the minimal version to install the system or would the Gnome version choosing "no desktop" be okay?

**Comment by khaneliman** [comment]
> Do you think I should use the minimal version to install the system or would the Gnome version choosing "no desktop" be okay?

Not really related to this config.. the NixOS installer is just going to guide you on partitioning your system and installing a default configuration itself. If you try and use someone else's flake you will need to have an understanding of some of the machine/host specific configurations that you need to tweak to make it work for you. The main thing being, hardware specific configuration elements. I have stuff in each of the systems/ related to the CPU/GPU/Disk layouts that will be different for you and you need to remove/update/add according to your system.  

I would recommend reading up on how NixOS works and get more understanding of what my flake is doing. https://zero-to-nix.com/concepts/nixos Basically, each of the modules for home/darwin/nixos contain all the configuration for programs, services, tools, etc that I use or have used but they just define something available to consume. The homes/user@host and systems/platform/host modules are where a system is actually calling those modules to piece together a system/home-manager definition.

**Comment by codeskin-r** [comment]
One question, should I use "sudo nixos-rebuild switch --flake .#(nixos in my case)?? Or just "sudo nixos-rebuild switch --flake ."?

**Comment by khaneliman** [comment]
> One question, should I use "sudo nixos-rebuild switch --flake .#(nixos in my case)?? Or just "sudo nixos-rebuild switch --flake ."?

Depends on use case. If you have a matching hostname system already, you dont need to provide the name of which system to build. If you want to make sure you activate your configuration of a specific system you can provide the name. The flake will find the system that matches your hostname by default.

**Comment by codeskin-r** [comment]
Okay! Thanksss, Thank you very much for all your help, honestly I have wanted to use your configuration for a long time and I still couldn't, I hope I can do it today, I will be communicating the results to you

**Comment by codeskin-r** [comment]
![20240630_024705](https://github.com/khaneliman/khanelinix/assets/159903896/dd1bfc2d-c432-4fc5-9899-f4f9112f2512)

Sorry for bothering, this happened to me now, what would be the solution?
